# analysis_options.yaml
# =====================
# This file configures lint rules (Analyzer rules).
# It helps catch bad practices early and enforces clean code style.

# 1️⃣ Inherit recommended Flutter rules
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # --------------------------
    # ✅ Const usage (performance + memory optimization)
    # --------------------------
    prefer_const_constructors: true
    # Example:
    #   Text("Hi")   ❌
    #   const Text("Hi") ✅

    prefer_const_literals_to_create_immutables: true
    # Example:
    #   final list = [1,2,3];  ❌
    #   const list = [1,2,3]; ✅

    prefer_const_declarations: true
    # Example:
    #   final pi = 3.14; ❌
    #   const pi = 3.14; ✅

    # --------------------------
    # ✅ Logging & debugging
    # --------------------------
    avoid_print: true
    # Prevent using print() → Use logger instead (e.g., debugPrint / developer.log)

    # --------------------------
    # ✅ Widgets
    # --------------------------
    avoid_unnecessary_containers: true
    # Warns if Container has no decoration/constraints and only wraps another widget
    # Example:
    #   Container(child: Text("Hi")) ❌
    #   Text("Hi") ✅

    # --------------------------
    # ✅ Formatting & style
    # --------------------------
    require_trailing_commas: true
    # Helps auto-formatting be cleaner (esp. in multi-line widgets)
    # Example:
    #   Column(
    #     children: [
    #       Text("One"),
    #       Text("Two")   ❌
    #     ],
    #   )
    #
    #   Column(
    #     children: [
    #       Text("One"),
    #       Text("Two"), ✅
    #     ],
    #   )

    prefer_final_locals: true
    # Forces local variables to be final if never reassigned
    # Example:
    #   var name = "Karem"; ❌
    #   final name = "Karem"; ✅

    unnecessary_this: true
    # Prevents writing "this." when not needed
    # Example:
    #   this.name = "Ali"; ❌ (inside class)
    #   name = "Ali"; ✅

    prefer_single_quotes: true
    # Enforce using single quotes for strings
    # Example:
    #   print("Hello"); ❌
    #   print('Hello'); ✅
