// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRjYgkVKflvI_oCCpYj2784Aig8BOpoRI',
    appId: '1:981577706681:web:2fb3ce74200a6e67bdbf68',
    messagingSenderId: '981577706681',
    projectId: 'depi-graduation-project',
    authDomain: 'depi-graduation-project.firebaseapp.com',
    storageBucket: 'depi-graduation-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDNGD0MtxjNGA4xhOHZ9uOcJYjGOm0zTw',
    appId: '1:981577706681:android:82f3f81f31619136bdbf68',
    messagingSenderId: '981577706681',
    projectId: 'depi-graduation-project',
    storageBucket: 'depi-graduation-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR5rbzLrE50jHCHx1a1MVOANHiwcE2zK4',
    appId: '1:981577706681:ios:803bb9062495aa02bdbf68',
    messagingSenderId: '981577706681',
    projectId: 'depi-graduation-project',
    storageBucket: 'depi-graduation-project.firebasestorage.app',
    iosBundleId: 'com.example.depiGraduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR5rbzLrE50jHCHx1a1MVOANHiwcE2zK4',
    appId: '1:981577706681:ios:803bb9062495aa02bdbf68',
    messagingSenderId: '981577706681',
    projectId: 'depi-graduation-project',
    storageBucket: 'depi-graduation-project.firebasestorage.app',
    iosBundleId: 'com.example.depiGraduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRjYgkVKflvI_oCCpYj2784Aig8BOpoRI',
    appId: '1:981577706681:web:09ab20d24faf8560bdbf68',
    messagingSenderId: '981577706681',
    projectId: 'depi-graduation-project',
    authDomain: 'depi-graduation-project.firebaseapp.com',
    storageBucket: 'depi-graduation-project.firebasestorage.app',
  );
}
